#pragma once
enum OBJID {OBJ_PLAYER, OBJ_MONSTER, OBJ_ITEM, OBJ_BULLET, OBJ_TOWER, OBJ_GYU_FLOAR, OBJ_END};
enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END};
enum SCENE {STAGE_SELECT, STAGE_ST, STAGE_GH, STAGE_YM, STAGE_HS, STAGE_HR, STAGE_END};
enum CHANNELID {SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER, SOUND_BULLET, SOUND_SYSTEM, MAXCHANNEL};
enum UIID {UI_BACKGROUND,UI_OBJ,UI_SYSTEM,UI_END};